name:                kriegspiel
version:             0.1.0
license:             NPOSL-3.0
author:              barsanges
maintainer:          https://github.com/barsanges
copyright:           2021 barsanges

extra-source-files:
- README.md

synopsis:            Literally a wargame
description:         Please see the README

dependencies:
- base
- containers

library:
  source-dirs: src